gallery/urls.py
from django.urls import path

from . import views

app_name = 'gallery'

urlpatterns = [
    path('', views.image_list, name='list'),
    path('<int:image_id>/', views.image_detail, name='detail'),
    path('add/', views.image_add, name='add'),
]

upload_image/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gallery.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/models.py
from django.db import models
from django.core.files import File
from urllib.request import urlopen
from tempfile import NamedTemporaryFile


class Image(models.Model):
    original_image = models.ImageField('Оригинальное изображение', upload_to='gallery/', blank=True, null=True)
    image = models.ImageField('Файл', upload_to='gallery/')
    alt = models.CharField('Альтернативный текст', max_length=256, blank=True, null=True)
    url = models.URLField('Ссылка', max_length=256, blank=True, null=True)

    def __str__(self):
        if self.alt:
            return self.alt
        return str(self.image)

    def get_image_by_url(self):
        img_temp = NamedTemporaryFile(delete=True)
        img_temp.write(urlopen(self.url).read())
        img_temp.flush()
        self.image.save(f"image_{self.pk}.jpg", File(img_temp))

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.url and not self.image:
            self.get_image_by_url()

    class Meta:
        verbose_name = 'Изображение'
        verbose_name_plural = 'Изображения'

gallery/forms.py
from PIL import Image as pillow_image
from django.core.files.base import ContentFile
from django.core.exceptions import ValidationError
from django import forms

from .models import Image


class ImageForm(forms.ModelForm):
    image = forms.ImageField(required=False, label='Файл')

    class Meta:
        model = Image
        fields = ('url', 'image',)

    def clean(self):
        cleaned_data = super().clean()
        url = cleaned_data.get('url')
        image = cleaned_data.get('image')

        if url and image:
            raise ValidationError('Вы указали одновременно два поля, выберите что-то одно.')
        elif not url and not image:
            raise ValidationError('Пожалуйста, укажите хотя бы одно поле.')


class ResizeForm(forms.ModelForm):
    width = forms.IntegerField(label='Ширина', required=False)
    height = forms.IntegerField(label='Высота', required=False)

    class Meta:
        model = Image
        fields = ('width', 'height')

    def save(self, commit=True):
        image_obj = super().save()

        # Оставляем оргинал в Image.original_image
        if not image_obj.original_image:
            pic_copy = ContentFile(image_obj.image.read())
            new_pic = image_obj.image.name.split('/')[-1]
            image_obj.original_image.save(new_pic, pic_copy)

        width = self.cleaned_data.get('width')
        height = self.cleaned_data.get('height')

        # Новая картинка с учетом пользовательского ввода
        image_pil = pillow_image.open(image_obj.original_image)
        if not width:
            width = image_pil.size[0]
        if not height:
            height = image_pil.size[0]
        image_pil.thumbnail((width, height), pillow_image.ANTIALIAS)
        image_pil.save(image_obj.image.path)

        return image_obj

gallery/views.py
from django.shortcuts import render, redirect

from .models import Image
from .forms import (ImageForm, ResizeForm)


def image_list(request):
    images = Image.objects.all()
    ctx = {
        'images': images,
    }
    return render(request, 'images/list.html', ctx)


def image_detail(request, image_id):
    image = Image.objects.get(pk=image_id)
    form = ResizeForm(request.POST or None, request.FILES or None, instance=image)
    if form.is_valid():
        form.save()
        return redirect('gallery:detail', image_id)
    ctx = {
        'image': image,
        'form': form,
    }
    return render(request, 'images/detail.html', ctx)


def image_add(request):
    form = ImageForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        img = form.save()
        return redirect('gallery:detail', img.pk)
    ctx = {
        'form': form,
    }
    return render(request, 'images/form.html', ctx)

templates/_base.html
<!doctype html>
<html lang="ru-Ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

    {% block content %}

    {% endblock %}

</body>
</html>

templates/images/detail.html
{% extends '_base.html' %}

{% block title %}
    {{ image }}
{% endblock %}

{% block content %}
    <a href="{% url 'gallery:list' %}">Назад к списку</a>
    <h1>{{ image }}</h1>
    <form action="{% url 'gallery:detail' image.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Отправить</button>
    </form>
    <img src="{{ image.image.url }}" alt="{{ image.alt }}">
{% endblock %}

templates/images/form.html
{% extends '_base.html' %}

{% block title %}
    Новое изображение
{% endblock %}

{% block content %}
    <a href="{% url 'gallery:list' %}">Назад к списку</a>
    <h1>Новое изображение</h1>
    <form action="{% url 'gallery:add' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Отправить</button>
    </form>
{% endblock %}

templates/images/list.html
{% extends '_base.html' %}

{% block title %}
    Список изображений
{% endblock %}

{% block content %}
    <h1>Список изображений</h1>
    {% for image in images %}
        <div>
            <a href="{% url 'gallery:detail' image.pk %}">
                <img src="{{ image.image.url }}" alt="{{ image.image.alt }}">
            </a>
        </div>
    {% empty %}
        <p>Нет доступных изображений</p>
    {% endfor %}

    <a href="{% url 'gallery:add' %}">Добавить изображение</a>
{% endblock %}